name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
- job: ChangeThePhoto
  displayName: 'Updates the photo in readme.md to a random new one'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    persistCredentials: true
  - task: ShellScript@2
  inputs:
    scriptPath: ./github/actions/scripts/changeimage.sh
