name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  my_first_job:
  steps:
    - name: Display the path
      run: ./github/actions/scripts/changeimage.ps1
      shell: pwsh
