name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  my_first_job:
    name: Change the photo
    runs-on: ubuntu-latest
    steps:
      - name: Change to a random image other image
        run: ./.github/actions/scripts/changeimage.ps1
        shell: pwsh
