name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  my_first_job:
    name: Change the photo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Change to a random image other image
        run: ./.github/actions/scripts/changeimage.ps1
        shell: pwsh
      - name: Commit back to repo
        uses: EndBug/add-and-commit@v4 # You can change this to use a specific version
          with:
            force: true
            message: 'Your commit message'
          env:
            # This is necessary in order to push a commit to the repo
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged