name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

jobs:
  my_first_job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh
